name = "text-hosting"
main = "src/worker.ts"
compatibility_date = "2024-10-17"

[[kv_namespaces]]
binding = ""
id = ""
preview_id = ""

[vars]
MAX_FILE_SIZE = "5242880"

[assets]
binding = "ASSETS"
directory = "dist"
